[package]
name = "management_app"
version = "0.1.0"
authors = ["Colin Diener <colin@colind.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# serial = "0.4.0"
serialport = "4.0.1"
# robust-arduino-serial = "0.1.1"
